export const homeObjOne = {
    id: 'Roots_of_Equations',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine: "หาค่า x ที่ทำให้ y เท่ากับ 0",
    headline: "Roots of Equations",
    descripttion:"ส่วนเนื้อหาโดย",
    buttonLabel:"เข้าสู่เนื้อหา",
    imgStart: true,
    img:require('../../images/svg-1.svg').default,
    alt:'picture1',
    dark:true,
    primary:true,
    darkText:false,
    lightBgCard:true,
    text: ["GraphicalMethod","BisectionMethod","FalsePosition","OnePointIteration",
    "NewtonRapson","SecantMethod"],
};
export const homeObjTwo= {
    id: 'Linear_Algibar',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine: "ใช้สมการเส้นตรงในการหาคำตอบ",
    headline: "Linear Algibar",
    descripttion:"ส่วนเนื้อหาโดย",
    buttonLabel:"เข้าสู่เนื้อหา",
    imgStart: false,
    img:require('../../images/svg-2.svg').default,
    alt:'picture2',
    dark:false,
    primary:false,
    darkText:true,
    lightBgCard:false,
    text: ["Cramer_Rule","GaussElimination","GaussJordan"
    ,"LU_Decomposition","JacobiIteration",
    "GaussSeidel_Iteration","ConjugateGradient"],
    
    
};
export const homeObjThree = {
    id: 'Interpolation',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine: "ค่าข้อมูลอยู่ภายในข้อมูลที่มี",
    headline: "Interpolation",
    descripttion:"ส่วนเนื้อหาโดย",
    buttonLabel:"เข้าสู่เนื้อหา",
    imgStart: true,
    img:require('../../images/svg-3.svg').default,
    alt:'picture3',
    dark:true,
    primary:true,
    darkText:false,
    lightBgCard:true,
    text: ["Newton_Divided","Lagrange_Polynomials","Spline_Interpolaation"],
};
export const homeObjFour = {
    id: 'Regression',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine: "ใช้จุด n จุด เพื่อหาสมการ",
    headline: "Regression",
    descripttion:"ส่วนเนื้อหาโดย",
    buttonLabel:"เข้าสู่เนื้อหา",
    imgStart: false,
    img:require('../../images/svg-4.svg').default,
    alt:'picture4',
    dark:false,
    primary:false,
    darkText:true,
    lightBgCard:false,
    text: ["Linear_Regression","Polynomial","Multiple_Linear"],
};
